CREATE TABLE SILVER.D_BLOCOS (
    CO_PAIS INT,
    CO_BLOCO INT,
    NO_BLOCO VARCHAR(255),
    NO_BLOCO_ING VARCHAR(255),
    NO_BLOCO_ESP VARCHAR(255)
);

CREATE TABLE SILVER.D_NCM (
    CO_NCM INT,
    CO_UNID INT,
    CO_SH6 INT,
    CO_PPE INT,
    CO_PPI INT,
    CO_FAT_AGREG INT,
    CO_CUCI_ITEM INT,
    CO_CGCE_N3 INT,
    CO_SIIT INT,
    CO_ISIC_CLASSE INT,
    CO_EXP_SUBSET INT,
    NO_NCM_POR VARCHAR(255),
    NO_NCM_ESP VARCHAR(255),
    NO_NCM_ING VARCHAR(255)
);

CREATE TABLE SILVER.D_NCM_ISIC (
    CO_ISIC_CLASSE INT,
    NO_ISIC_CLASSE VARCHAR(255),
    NO_ISIC_CLASSE_ING VARCHAR(255),
    NO_ISIC_CLASSE_ESP VARCHAR(255),
    CO_ISIC_GRUPO INT,
    NO_ISIC_GRUPO VARCHAR(255),
    NO_ISIC_GRUPO_ING VARCHAR(255),
    NO_ISIC_GRUPO_ESP VARCHAR(255),
    CO_ISIC_DIVISAO INT,
    NO_ISIC_DIVISAO VARCHAR(255),
    NO_ISIC_DIVISAO_ING VARCHAR(255),
    NO_ISIC_DIVISAO_ESP VARCHAR(255),
    CO_ISIC_SECAO VARCHAR(255),
    NO_ISIC_SECAO VARCHAR(255),
    NO_ISIC_SECAO_ING VARCHAR(255),
    NO_ISIC_SECAO_ESP VARCHAR(255)
);

CREATE TABLE SILVER.D_NCM_SH (
    CO_SH6 INT,
    NO_SH6_POR VARCHAR(255),
    NO_SH6_ESP VARCHAR(255),
    NO_SH6_ING VARCHAR(255),
    CO_SH4 INT,
    NO_SH4_POR VARCHAR(255),
    NO_SH4_ESP VARCHAR(255),
    NO_SH4_ING VARCHAR(255),
    CO_SH2 INT,
    NO_SH2_POR VARCHAR(255),
    NO_SH2_ESP VARCHAR(255),
    NO_SH2_ING VARCHAR(255),
    CO_NCM_SECROM VARCHAR(255),
    NO_SEC_POR VARCHAR(255),
    NO_SEC_ESP VARCHAR(255),
    NO_SEC_ING VARCHAR(255)
);

CREATE TABLE SILVER.D_PAIS (
    CO_PAIS INT,
    CO_PAIS_ISON3 INT,
    CO_PAIS_ISOA3 VARCHAR(255),
    NO_PAIS VARCHAR(255),
    NO_PAIS_ING VARCHAR(255),
    NO_PAIS_ESP VARCHAR(255)
);

CREATE TABLE SILVER.D_UF (
    CO_UF INT,
    SG_UF VARCHAR(255),
    NO_UF VARCHAR(255),
    NO_REGIAO VARCHAR(255)
);

CREATE TABLE SILVER.D_UNIDADE (
    CO_UNID INT,
    NO_UNID VARCHAR(255),
    SG_UNID VARCHAR(255)
);

CREATE TABLE SILVER.D_URF (
    CO_URF INT,
    NO_URF VARCHAR(255)
);

CREATE TABLE SILVER.D_VIA (
    CO_VIA INT,
    NO_VIA VARCHAR(255)
);

CREATE TABLE SILVER.F_EXPORTACOES_ESTADOS (
    CO_ANO INT,
    CO_MES INT,
    CO_NCM INT,
    CO_UNID INT,
    CO_PAIS INT,
    SG_UF_NCM VARCHAR(255),
    CO_VIA INT,
    CO_URF INT,
    QT_ESTAT INT,
    KG_LIQUIDO INT,
    VL_FOB INT
);

CREATE TABLE SILVER.F_IMPORTACOES_ESTADOS (
    CO_ANO INT,
    CO_MES INT,
    CO_NCM INT,
    CO_UNID INT,
    CO_PAIS INT,
    SG_UF_NCM VARCHAR(255),
    CO_VIA INT,
    CO_URF INT,
    QT_ESTAT INT,
    KG_LIQUIDO INT,
    VL_FOB INT,
    VL_FRETE INT,
    VL_SEGURO INT
);
