-- Criar os schemas
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE SCHEMA IF NOT EXISTS LOGS;

-- Criar a tabela PIPELINE_EXECUCOES no schema LOGS
CREATE TABLE IF NOT EXISTS LOGS.PIPELINE_EXECUCOES (
    TASK_ID SERIAL PRIMARY KEY,
    NM_PIPELINE VARCHAR(255) NOT NULL,
    TEMA VARCHAR(255),
    CAMADA VARCHAR(50),
    TEMPO_EXECUCAO INTERVAL,
    DATA_EXECUCAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ULTIMA_ATUALIZACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Criar a tabela TABELAS_INDICADORES no schema LOGS
CREATE TABLE IF NOT EXISTS LOGS.TABELAS_INDICADORES (
    ID SERIAL PRIMARY KEY,
    NM_TABELA VARCHAR(255) NOT NULL,
    NM_PIPELINE VARCHAR(255),
    QTD_LINHAS INTEGER,
    QTD_COLUNAS INTEGER,
    TAMANHO_KB NUMERIC(10,2),
    DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ULTIMA_ATUALIZACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
