-- Criar os schemas
CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;
CREATE SCHEMA IF NOT EXISTS logs;

-- Criar a tabela PIPELINE_EXECUCOES no schema logs
CREATE TABLE IF NOT EXISTS logs.PIPELINE_EXECUCOES (
    TASK_ID SERIAL PRIMARY KEY,
    NM_PIPELINE VARCHAR(255) NOT NULL,
    TEMA VARCHAR(255),
    CAMADA VARCHAR(50),
    TEMPO_EXECUCAO INTERVAL,
    DATA_EXECUCAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ULTIMA_ATUALIZACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Criar a tabela TABELAS_INDICADORES no schema logs
CREATE TABLE IF NOT EXISTS logs.TABELAS_INDICADORES (
    id SERIAL PRIMARY KEY,
    nm_tabela VARCHAR(255) NOT NULL,
    nm_pipeline VARCHAR(255),
    qtd_linhas INTEGER,
    qtd_colunas INTEGER,
    tamanho_kb NUMERIC(10,2),
    data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultima_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
